export const ACTION_TYPE = {
  ADDED_TO_BOOKMARK: "ADDED_TO_BOOKMARK",
  REMOVE_FROM_BOOKMARK: "REMOVE_FROM_BOOKMARK",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  LIKE: "LIKE",
  DISLIKE: "DISLIKE",
  GET_ALL_USER: "GET_ALL_USER",
  GET_USER: "GET_USER",
  UPDATE_USER: "UPDATE_USER",
};
