export const ACTION_TYPE = {
  ADDED_TO_BOOKMARK: "ADDED_TO_BOOKMARK",
  REMOVE_FROM_BOOKMARK: "REMOVE_FROM_BOOKMARK",
  FOLLOW: "FOLLOW",
  UNFOLLOW: "UNFOLLOW",
  LIKE: "LIKE",
  DISLIKE: "DISLIKE",
};
